#!/bin/bash
#

REPO_ROOT=$(git rev-parse --show-toplevel)
FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD)
my_dir="$(dirname "$0")"
source $my_dir/functions/common.txt
source $my_dir/functions/php.txt
source $my_dir/functions/javascript.txt
has_errors=false

for file in $(changed_php_files)
do
    errors=$(php_lint $file; xdebug_grep $file)
    if [[ "$errors" ]]
    then
        print_error $file
        has_errors=true
    fi
done

if $has_errors; then
    echo -e "\nFIX THIS FUCKING PHP PARSE ERRORS DUDE"
fi

if find_js_debug; then
    echo "Aborted Commit"
    exit 1
fi

exit 1